### ISSUE TITLE
Port over patchbay-dark-crystal code and remove Patchbay and Tabs

### ISSUE THREAD

**Issue by KGibb8** [blockades/dark-crystal-standalone#1]
Working towards a more user-friendly and lean / stripped back standalone client, we should move towards stripping out Patchbay and using just Patchcore. Currently patchbay gives us extra plugins which we don't want (see https://github.com/blockades/dark-crystal-standalone/blob/55ffc8d8f38d93504904e531692e6fc9a2ae1cfe/main.js#L14).

```
// NOTE - the following two plugins are needed because the /calendar page expects things from them. That needs extracting, or these plugins need to provide dummy plugs to stop the app exploding!
  plugins.gatherings,
  plugins.scry,
```

Decoupling from Patchbay means porting our code over from [`patchbay-dark-crystal`](https://github.com/blockades/patchbay-dark-crystal) as it will no longer be used as a plugin in the standalone.

Removing Hypertabs will mean the router will need rewriting / simplifying.

Overall, this will make our UI significantly more open / flexible / versatile and position us well for future design iterations.

## TODOs:
- [ ] Remove Patchbay
- [ ] Remove Hypertabs
- [ ] Ensure required depject modules are still present in the application
- [ ] Setup an ssb config file and a server
- [ ] Configure electron to start the server as a background process
- [ ] Simplify the router to render our views
- [ ] Edit `app/html/app` to render views  based on the router

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 250.0 DAI (250.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $95,178.61 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [nanspro](https://gitcoin.co/profile/nanspro) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?mutate_worker_action=approve&worker=nanspro) | [reject worker](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?mutate_worker_action=reject&worker=nanspro))_.**

I am going through patchbay, patchbay-dark-crystal first to setup the environment locally, will ask if any questions on the issue itself.
The project looks pretty interesting and definitely useful so would love to contribute to it!!!

ETA: I am about to finish one task tonight so can start on this from tomorrow if approved :)

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994).

**Comment by nanspro** [comment]
@ceresstation i guess this issue is meant for @KGibb8  so stopping now. let me know if there's any other bounty related to dark-crystal :)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=1) | [3 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=3) | [5 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=5) | [10 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=10) | [100 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=1) | [3 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=3) | [5 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=5) | [10 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=10) | [100 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=1) | [3 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=3) | [5 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=5) | [10 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=10) | [100 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=1) | [3 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=3) | [5 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=5) | [10 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=10) | [100 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 250.0 DAI (250.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@kgibb8](https://gitcoin.co/profile/kgibb8)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/blockades/dark-crystal-standalone/pull/13) by @KGibb8

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $71,096.98 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 250.0 DAI (250.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @KGibb8.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/1/2994)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $78,235.31 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
