### ISSUE TITLE
Notification of Received Shard

### ISSUE THREAD

**Issue by KGibb8** [blockades/dark-crystal-standalone#2]
> As a peer, it would be helpful to receive a push notification stating that a request to return a shard has been received, along with a text alert to contact the secret originator, in order to check that this request was authentic / valid.

## TODOs:
- [ ] wireframe an intuitive notifications area / view
- [ ] execute query for shards at top-level of views
- [ ] use wireframe to implement interface - render a notification based on the pulled data
- [ ] ensure notifications area is agnostic / is extensible for other notification types
- [ ] use ssb-unread plugin for marking notification as received and read
