### ISSUE TITLE
Notification of "shard received" by secret holder

### ISSUE THREAD

**Issue by KGibb8** [blockades/dark-crystal-standalone#4]
> As a secret holder, I would like to receive a notification that shards that I have sent to my peers have been received, so that I am safe in the knowledge that my secret is safe.

Follow up to https://github.com/blockades/dark-crystal-standalone/issues/2 (notifications)

## TODOs
- [ ] from the perspective of the custodian, write a flumeview that listens for shard messages arriving and publish an acknowledgement message for any shards received
- [ ] from the perspective of the secret holder, listen for acknowledgement messages and render them as notifications
- [ ] use ssb-unread to mark notifications as read
