### ISSUE TITLE
Help area with how-to-use instructions and a link to a tutorial video

### ISSUE THREAD

**Issue by KGibb8** [blockades/dark-crystal-standalone#5]
> As a peer, I would like to be able to navigate to a 'help' section where I can view a clear set of instructions on how to use the application.

## TODOs
- [ ] Add a help icon (?) which renders a help view (new route, new view)
- [ ] Write clear how-to-use the application content
- [ ] Create a tutorial video
- [ ] Persist and reference the tutorial video somehow - this could be embedded or a link.
  - Could use Dat or the Dark Crystal server to persist the video
