### ISSUE TITLE
New Crystal form improvements - quorum slider and a 'trust indicator'

### ISSUE THREAD

**Issue by KGibb8** [blockades/dark-crystal-standalone#6]
> As a peer, when creating a new dark crystal, I would like to use a slider to indicate the quorum. This is a visually intuitive way of preventing me from choosing a quorum of 1 (which is invalid).

> As a peer, when I select 2 or more custodians, a slider appears below which enables me to indicate the desired quorum.

> As a peer, when moving the quorum slider or changing the number of custodians, I would like a visual indicator to dynamically show my the level of trust this quorum / number of custodians implies.

> As a peer, which completing the new crystal form, I should only see the 'submit' button when I have completed all the necessary fields.

## TODOs
- [ ] Wireframe a new Dark Crystal form that includes the relevant fields, a dynamic slider and a dynamic trust indicator
- [ ] Rewrite the form to include a dynamic slider that adjusts its maximum based on the number of custodians selected. It should permit no less than a quorum of 2. This should remove the need to render custom errors as the interface simply won't allow an unintuitive use.
- [ ] Devise 'trust bands' that make a secret holder aware of the risks of sharing a secret under different scenarios based on the quorum and number of custodians.
- [ ] Render these trust-bands dynamically as a process bar with different colours.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/6/2996).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/blockades/dark-crystal-standalone/6/2996).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $96,642.24 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gutsal-arsen** [comment]
There is some problem building that:
![image](https://user-images.githubusercontent.com/1643117/57921138-51462800-78a5-11e9-93b0-9cf627d9eef1.png)


OS: Linux trussardi 4.19.27-gentoo-r1 #6 SMP Fri Apr 12 17:28:21 EEST 2019 x86_64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz GenuineIntel GNU/Linux

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [brown2rl](https://gitcoin.co/profile/brown2rl) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/blockades/dark-crystal-standalone/6/2996?mutate_worker_action=approve&worker=brown2rl) | [reject worker](https://gitcoin.co/issue/blockades/dark-crystal-standalone/6/2996?mutate_worker_action=reject&worker=brown2rl))_.**

We could use InVision app to create the interactive wireframe, and then write the form in the language that works best.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/6/2996).

**Comment by gutsal-arsen** [comment]
@KGibb8 regarding my previous comment. `npm i` works as expected if I remove `"#dark-crystal-2"` part from `"patchbay": "github:ssbc/patchbay#dark-crystal-2"`

Will create PR now.

**Comment by gutsal-arsen** [comment]
Also found that:
![image](https://user-images.githubusercontent.com/1643117/57964948-cd904800-7945-11e9-9e54-972786997ce2.png)


PR #13 created.

**Comment by gutsal-arsen** [comment]
@KGibb8  I guess you need to take a look yourself. Application does not open main window as there's no `server.js` in `node_modules/patchbay*` package.

**Comment by PixelantDesign** [comment]
@KGibb8 you have 4 applicants above!

**Comment by gutsal-arsen** [comment]
@KGibb8 anyone is working on that issue as I can take it?

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 500.0 DAI (500.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@kgibb8](https://gitcoin.co/profile/kgibb8)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/blockades/dark-crystal-standalone/pull/14) by @KGibb8

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/6/2996)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/blockades/dark-crystal-standalone/6/2996).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $76,545.61 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @KGibb8.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/6/2996)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $78,735.31 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
