### ISSUE TITLE
Search for users or crystals

### ISSUE THREAD

**Issue by KGibb8** [blockades/dark-crystal-standalone#7]
> As a peer, when I navigate to my list of Dark Crystals, I would like a mechanism to sort of filter my secrets

> As a peer, I should be able to search for other scuttlebutt users under a search bar

## TODOs
- [ ] add a search bar input field 
- [ ] suggest either users (based on name or ID) or existing crystals / secrets (based on name)
- [ ] navigate to the relevant view (a profile view if a user, or a crystals/show view if a crystal / secret)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 250.0 DAI (250.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $96,142.24 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [iamonuwa](https://gitcoin.co/profile/iamonuwa) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?mutate_worker_action=approve&worker=iamonuwa) | [reject worker](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?mutate_worker_action=reject&worker=iamonuwa))_.**

Awesome task. I would love to pick this up and get it done. ETA 1 day.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [iamonuwa](https://gitcoin.co/profile/iamonuwa) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?mutate_worker_action=approve&worker=iamonuwa) | [reject worker](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?mutate_worker_action=reject&worker=iamonuwa))_.**

Awesome task. I would love to pick this up and get it done. ETA 1 day.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995).

**Comment by frankchen07** [comment]
@KGibb8 - frank from gitcoin here - any progress on this task? If not, we will release the bounty to the public.

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=1) | [3 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=3) | [5 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=5) | [10 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=10) | [100 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=1) | [3 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=3) | [5 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=5) | [10 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=10) | [100 days](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995?snooze=100)

**Comment by KGibb8** [comment]
@frankchen07 yes progress has been made, been working on the other outstanding issue!

**Comment by KGibb8** [comment]
https://github.com/blockades/dark-crystal-standalone/pull/15

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 250.0 DAI (250.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@kgibb8](https://gitcoin.co/profile/kgibb8)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/blockades/dark-crystal-standalone/pull/15) by @KGibb8

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $76,906.58 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 250.0 DAI (250.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @KGibb8.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/blockades/dark-crystal-standalone/7/2995)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $78,485.31 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
