### ISSUE TITLE
Rework the interface for a mobile-first design

### ISSUE THREAD

**Issue by KGibb8** [blockades/dark-crystal-standalone#8]
In the interests of the possibility of future collaboration with Manyverse and the hope that this could one day be a mobile application, the interface demands a rework that takes a mobile-first approach.

## TODOs
- [ ] wireframe several ideas for different interfaces
- [ ] get peer review of the wireframes
- [ ] select one an implement it
- [ ] rework the views
- [ ] rework the entire applications styling

## Nice to Haves:
- [ ] Add light and dark themes
